### ISSUE TITLE
Printing named variables

### ISSUE THREAD

**Issue by ak3n** [jonsterling/hs-abt#9]
Hi!

I changed `x <- fresh` to `x <- named "x"`. Is it correct behaviour that named variable `x` still gets printed as nameless?

<img width="465" alt="screen shot 2017-06-08 at 01 31 17" src="https://user-images.githubusercontent.com/588373/26899969-412df9e6-4bea-11e7-820d-666712a70469.png">

**Comment by jonsterling** [comment]
I don't remember if I made it store names along with bound variables... it's very possible that I did not. I won't be maintaining this library (I don't want to do haskell anymore), but if you are interested in it, I could gladly transfer ownership to you.

**Comment by ak3n** [comment]
I think that adding me to the repository is enough. I will try to fix it. Thanks!
